# Site settings
title: "MethAL: Methodology in Artifial Life"
email: "students+owner@isal.groups.io"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: "@isalstudents"
github_username: eralife

# Build settings
markdown: kramdown
